// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-wm3E_mCLP-iOj4j07w4LKE2S0Xyi8g',
    appId: '1:134177399956:web:6e8afef8d85cddc2c94081',
    messagingSenderId: '134177399956',
    projectId: 'lab-test-de28b',
    authDomain: 'lab-test-de28b.firebaseapp.com',
    storageBucket: 'lab-test-de28b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctFuRrXUCMwuGCYtt5HAUGEx-oZd8y8A',
    appId: '1:134177399956:android:7e658acc39f836c2c94081',
    messagingSenderId: '134177399956',
    projectId: 'lab-test-de28b',
    storageBucket: 'lab-test-de28b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwK2TCdMrYOUE3dugk29sn-R5CaOIrfBk',
    appId: '1:134177399956:ios:1fc930337c832fc6c94081',
    messagingSenderId: '134177399956',
    projectId: 'lab-test-de28b',
    storageBucket: 'lab-test-de28b.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwK2TCdMrYOUE3dugk29sn-R5CaOIrfBk',
    appId: '1:134177399956:ios:1fc930337c832fc6c94081',
    messagingSenderId: '134177399956',
    projectId: 'lab-test-de28b',
    storageBucket: 'lab-test-de28b.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp-wm3E_mCLP-iOj4j07w4LKE2S0Xyi8g',
    appId: '1:134177399956:web:8d627afa3777456dc94081',
    messagingSenderId: '134177399956',
    projectId: 'lab-test-de28b',
    authDomain: 'lab-test-de28b.firebaseapp.com',
    storageBucket: 'lab-test-de28b.firebasestorage.app',
  );
}
